name: Deploy to VPS

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the latest code from the repository

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Set up Node.js environment
      with:
        node-version: '18'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Build project
      run: npm run build  # Build the Vue.js project

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.3  # Use the SCP action to deploy via SSH
      with:
        host: ${{ secrets.REMOTE_HOST }}  # The IP address of your VPS (213.165.91.221)
        username: ${{ secrets.REMOTE_USER }}  # The username for your VPS (jd)
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Private SSH key added to repository secrets
        port: 4020  # Custom SSH port for your VPS
        source: "dist/*"  # Source files to be copied
        target: "/var/www/jdwd40.com/html"  # Target directory on your VPS

    - name: Restart Nginx
      uses: appleboy/ssh-action@master  # Use the SSH action to execute commands on your VPS
      with:
        host: ${{ secrets.REMOTE_HOST }}  # The IP address of your VPS (213.165.91.221)
        username: ${{ secrets.REMOTE_USER }}  # The username for your VPS (jd)
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Private SSH key added to repository secrets
        port: 4020  # Custom SSH port for your VPS
        script: |
          sudo systemctl restart nginx  # Restart Nginx to apply the changes
