name: Deploy to VPS

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci  # Use 'npm ci' for cleaner, more reliable builds

    - name: Build project
      run: npm run build

    - name: List dist contents
      run: ls -R dist

    - name: Create test file
      run: echo "Test deployment $(date)" > dist/test.txt

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 4020
        source: "dist/*"
        target: "/var/www/jdwd40.com/html"
        strip_components: 1  # Remove the 'dist' directory from the path

    - name: Verify deployment and restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 4020
        script: |
          echo "Contents of /var/www/jdwd40.com/html:"
          ls -la /var/www/jdwd40.com/html
          echo "Content of test.txt:"
          cat /var/www/jdwd40.com/html/test.txt
          echo "Restarting Nginx..."
          sudo systemctl restart nginx
          echo "Nginx restarted."